repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: eeee35a89e69d5772bdee97db1a6a898467b686e  # v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80  # v0.15.12
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
